In [18]:
%matplotlib inline

In [19]:
import numpy as np
from sklearn.svm import SVR
import matplotlib.pyplot as plt
import pandas as pd

In [20]:
import tensorflow
tensorflow.keras.__version__

'2.4.0'

In [21]:
weather = pd.read_csv('sonomavalley.csv')
weather.head()

,Unnamed: 0,winery,vintage,points,cities,MarchLowTemp,MarchHighTemp,MarchAvgTemp,MarchPrecip,MarchCloudiness,...,JulyAvgTemp,JulyPrecip,JulyCloudiness,JulyHumidity,AugLowTemp,AugHighTemp,AugAvgTemp,AugPrecip,AugCloudiness,AugHumidity
0,5,Iron Horse,2009,91,Sebastopol,49.903226,71.322581,63.258065,2.3,46.354839,...,47.129032,4.2,69.258065,87.322581,41.483871,55.516129,50.225806,5.1,67.419355,81.774194
1,6,Novy,2009,87,Healdsburg,41.548387,60.677419,53.193548,5.7,26.129032,...,75.903226,0.0,2.580645,52.064516,55.451613,82.838710,73.935484,0.1,4.967742,54.612903
2,7,Iron Horse,2010,92,Sebastopol,52.935484,72.419355,64.903226,5.5,42.741935,...,46.677419,1.9,74.161290,90.483871,36.548387,50.032258,44.806452,7.8,79.741935,91.290323
3,8,Iron Horse,2011,91,Sebastopol,50.806452,68.451613,61.677419,2.7,56.064516,...,46.225806,1.5,75.258065,90.096774,39.774194,56.580645,50.258065,4.2,65.741935,86.258065
4,9,River Road,2011,84,Guttenberg,32.451613,44.290323,39.580645,8.6,40.838710,...,79.354839,6.6,20.387097,77.645161,67.225806,80.935484,75.419355,18.6,24.741935,79.451613

In [22]:
weatherClean=weather.drop("Unnamed: 0", axis=1)
weatherClean.head()

,winery,vintage,points,cities,MarchLowTemp,MarchHighTemp,MarchAvgTemp,MarchPrecip,MarchCloudiness,MarchHumidity,...,JulyAvgTemp,JulyPrecip,JulyCloudiness,JulyHumidity,AugLowTemp,AugHighTemp,AugAvgTemp,AugPrecip,AugCloudiness,AugHumidity
0,Iron Horse,2009,91,Sebastopol,49.903226,71.322581,63.258065,2.3,46.354839,71.225806,...,47.129032,4.2,69.258065,87.322581,41.483871,55.516129,50.225806,5.1,67.419355,81.774194
1,Novy,2009,87,Healdsburg,41.548387,60.677419,53.193548,5.7,26.129032,70.935484,...,75.903226,0.0,2.580645,52.064516,55.451613,82.838710,73.935484,0.1,4.967742,54.612903
2,Iron Horse,2010,92,Sebastopol,52.935484,72.419355,64.903226,5.5,42.741935,72.870968,...,46.677419,1.9,74.161290,90.483871,36.548387,50.032258,44.806452,7.8,79.741935,91.290323
3,Iron Horse,2011,91,Sebastopol,50.806452,68.451613,61.677419,2.7,56.064516,79.483871,...,46.225806,1.5,75.258065,90.096774,39.774194,56.580645,50.258065,4.2,65.741935,86.258065
4,River Road,2011,84,Guttenberg,32.451613,44.290323,39.580645,8.6,40.838710,78.548387,...,79.354839,6.6,20.387097,77.645161,67.225806,80.935484,75.419355,18.6,24.741935,79.451613

In [23]:
# Data Pre-Processing

In [24]:
weatherClean.columns

Index(['winery', 'vintage', 'points', 'cities', 'MarchLowTemp',
       'MarchHighTemp', 'MarchAvgTemp', 'MarchPrecip', 'MarchCloudiness',
       'MarchHumidity', 'AprilLowTemp', 'AprilHighTemp', 'AprilAvgTemp',
       'AprilPrecip', 'AprilCloudiness', 'AprilHumidity', 'MayLowTemp',
       'MayHighTemp', 'MayAvgTemp', 'MayPrecip', 'MayCloudiness',
       'MayHumidity', 'JuneLowTemp', 'JuneHighTemp', 'JuneAvgTemp',
       'JunePrecip', 'JuneCloudiness', 'JuneHumidity', 'JulyLowTemp',
       'JulyHighTemp', 'JulyAvgTemp', 'JulyPrecip', 'JulyCloudiness',
       'JulyHumidity', 'AugLowTemp', 'AugHighTemp', 'AugAvgTemp', 'AugPrecip',
       'AugCloudiness', 'AugHumidity'],
      dtype='object')

In [25]:
weatherCleandf = weatherClean.drop(['winery', 'vintage', 'cities'], axis=1)

In [28]:
X = weatherCleandf.drop(['points'], axis=1).values.astype(float)
y = weatherCleandf['points'].values.astype(float).reshape(-1, 1)

In [29]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y)

In [30]:
regressor = SVR(kernel='rbf')
regressor.fit(X,y)

C:\Users\katty\Anaconda3\envs\PythonData\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

SVR()

In [33]:
X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(X, y, color = 'red')
plt.plot(X_grid, regressor.predict(X_grid), color = 'blue')
plt.title('Truth or Bluff (Support Vector Regression Model(High Resolution))')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()