In [1]:
# Set the seed value for the notebook so the results are reproducible
from numpy.random import seed
seed(1)

In [2]:
# Dependencies
import numpy as np
import pandas as pd

In [3]:
import tensorflow
tensorflow.keras.__version__

'2.4.0'

In [4]:
sonoma = pd.read_csv('sonomavalley.csv')
sonoma.head()

,Unnamed: 0,index,winery,vintage,cities,MarchLowTemp,MarchHighTemp,MarchAvgTemp,MarchPrecip,MarchCloudiness,...,JulyAvgTemp,JulyPrecip,JulyCloudiness,JulyHumidity,AugLowTemp,AugHighTemp,AugAvgTemp,AugPrecip,AugCloudiness,AugHumidity
0,5,14,Iron Horse,2009,Sebastopol,49.903226,71.322581,63.258065,2.3,46.354839,...,47.129032,4.2,69.258065,87.322581,41.483871,55.516129,50.225806,5.1,67.419355,81.774194
1,6,15,Novy,2009,Healdsburg,41.548387,60.677419,53.193548,5.7,26.129032,...,75.903226,0.0,2.580645,52.064516,55.451613,82.838710,73.935484,0.1,4.967742,54.612903
2,7,17,Iron Horse,2010,Sebastopol,52.935484,72.419355,64.903226,5.5,42.741935,...,46.677419,1.9,74.161290,90.483871,36.548387,50.032258,44.806452,7.8,79.741935,91.290323
3,8,20,Iron Horse,2011,Sebastopol,50.806452,68.451613,61.677419,2.7,56.064516,...,46.225806,1.5,75.258065,90.096774,39.774194,56.580645,50.258065,4.2,65.741935,86.258065
4,9,22,River Road,2011,Guttenberg,32.451613,44.290323,39.580645,8.6,40.838710,...,79.354839,6.6,20.387097,77.645161,67.225806,80.935484,75.419355,18.6,24.741935,79.451613